name: dio_cache_plus
description: "Enhanced Dio caching interceptor with per-request control, conditional caching, and expiration."
version: 1.0.2
homepage: https://github.com/BaluVadivel/dio_cache_plus
repository: https://github.com/BaluVadivel/dio_cache_plus.git
issue_tracker: https://github.com/BaluVadivel/dio_cache_plus/issues
documentation: https://github.com/BaluVadivel/dio_cache_plus#readme

license: MIT

topics:
  - dio
  - caching
  - http
  - interceptor
  - performance

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  hive_generator: ^2.0.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
